
name: Terraform CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::998230061098:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Verify Terraform Installation
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -recursive new-tr/


      - name: Terraform Init
        run: terraform -chdir=new-tr/root init

      - name: Terraform Validate
        run: terraform -chdir=new-tr/root validate

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Initialize TFLint
        run: tflint --init
        working-directory: new-tr/root

      - name: Run TFLint
        run: tflint
        working-directory: new-tr/root
        
      - name: Run tfsec Security Scan
        uses: tfsec/tfsec-sarif-action@master
        with:
          working_directory: new-tr/root
          sarif_file: tfsec.sarif
          tfsec_args: >
            --minimum-severity HIGH

      - name: Upload tfsec SARIF Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-sarif-report
          path: tfsec.sarif

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: new-tr/root
          framework: terraform
          quiet: true
          soft_fail: false
          output_format: sarif,json
          output_file_path: checkov.sarif,checkov.json

      - name: Upload Checkov SARIF Report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

      - name: Upload Checkov Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-security-report
          path: |
            checkov.sarif
            checkov.json
